
UIButton *BBone;
UIButton *BBone2;
UIButton *BBonebenphai;
UIButton *BBonebenphai2;
UIButton *BBoneLogV1, *BBoneLogV2;

ImFont *_espFont;
ImFont *_iconFont;
UILabel *label6;
UIView *view;
NSString *jail;
NSString *namedv;
NSString *deviceType;
NSString *bundle;
NSString *ver;
NSUserDefaults *saveSetting = [NSUserDefaults standardUserDefaults];
NSFileManager *fileManager1 = [NSFileManager defaultManager];
NSString *documentDir1 = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
std::string namereal;
std::string nameP;
size_t ActorLinkerOffField[50];
std::string heroname;
bool isAutoSellEnabled = false;
static bool MenDeal = false;
static bool Aimv1 = false;
static bool va3 = false;
static bool h1 = false;
static bool highfps = false;
static bool Map = false;
//static bool Map = false;
static bool hideuid = true;
static bool avt = false;
static bool his = false;
static bool h3 = false;
static bool unti = false;
static bool name = false;
static bool qualink = false;
static bool quafile = false;
static bool modsanh = false;
static bool xoamod = false;
static bool xoasanh = false;
static bool hidehis = false;
static bool hideban = false;
static bool hideinfo = false;
static bool ESPArrow = false;
static bool all = false;
static bool sell = false;
static bool autowin = false;
static bool kos = false;
static bool vang = false;
static bool va1 = false;
static bool va6 = false;
static bool tran = false;
static int banner = 1;
static int cac = 2;
bool ESP3DBox = false;
float distan = 25.0f;
static bool hideline = false;
static bool hidebox = false;
static bool hideinfoo = false;
static bool lockcam = false;
static bool hidearrow = false;
static bool hidedistance = false;
int skillCDStyle = 2;
uintptr_t botro;
uintptr_t c1;
uintptr_t c2;
uintptr_t c3;
bool showNameTimer = true;
float nameTimer = 0.0f;
const float NAME_DISPLAY_DURATION = 2.0f;
bool PlayerBox;
bool PlayerHealth;
bool PlayerAlert;
int minimapType = 1;
bool PlayerCd;
bool Anten;
int aiCount = 0;
int playerCount = 0;
float distanceesp = 150.0f;
int box = 0;
const char *box_items[3] = {"2D Box", "3D Box", "Border Box"};
int CameraHeight;
bool IgnoreInvisible;
float Dis = 1.0f;
int boxMode = 0;
bool isPlayerName;
bool autott;
bool Ksbs;
bool autobocpha;
int slot;
bool bua;
bool kheuoc;
bool autoliem;
bool rongta;           // rồng - tà thần
bool (*_sting)(void *ins);
bool (*Reqskill2)(void *ins,bool bForce);
bool (*Reqskill)(void *ins);
void (*_Skslot)(void *ins, int del);
void *Lmyactor = NULL, *Lactor = NULL, *ActorLK = NULL;
struct HeroWrapSkillData {
    int SkillId;
    int skillSlotCDMax;
    int skillLv;
    const char *skillIconPath;
    bool skillSlotUnlock;
    bool skillSlotReady;
    int Skill1SlotCD;
};
HeroWrapSkillData (*LHeroWrapper_GetHeroWrapSkillData)(void *instance, int slot);
int (*GetCurSkillSlotType)(void *instance);
int (*LActorRoot_get_ObjID)(void *instance);
void* (*get_main)();
Vector3 (*WorldToScreens)(void*, Vector3, int);
void* (*LActorRoot_get_PlayerMovement)(void *instance);
int (*get_speed)(void *instance);

bool ESPEnable;
bool autoyue;

bool wasUnlockhaDisabled = false;
bool wasUnlockbuttonDisabled = false;
bool wasunlockskinDisabled = false;
bool antihoc;
bool endnhanh;
bool tdkt;
bool sendsync;
bool AutoWin = false;
bool AutoLose = false;
void (*ForceKillCrystal)(int camp) = nullptr;
void* myLactorRoot = nullptr;
void* LGameActorMgr_Instance = nullptr;
void* myActorLinker = nullptr;
void* LLogicCore_Instance = nullptr;
bool autolog3p2ss;
bool checkautolog;
bool startcheck;
bool autotulen;
bool automing;
int (*get_SkillID)(void* instance);
int (*ActorLinker_get_ObjID)(void *instance);
int myObjID = 0;
bool isFliped;
int (*ActorLinker_get_playerId)(void *instance);
void* (*ActorLinker_AsHero)(void* instance);

bool autoflo;
bool mua;
bool combo1;
bool combo2;
bool combo3;
bool combo0 = true;
bool HoaPos;
float nguongmautulen;
bool mingcap8;
bool mingcap12;
bool congcongphep;
float nguongmauming;
float nguongmaucuoicung;
int giapphep;
float congtrudame;
bool autoveres;
float nguongmauveres;
bool useVeres;
bool ghostAdded;
bool ghostAdded2;
bool LogAddedV1;
bool LogAddedV2;
 
bool autobando;
bool autobandobenphai;
bool nutlogv1;
bool nutlogv2;
bool botrotab = true;
bool macrotab = false;
bool minimaptab;
bool modtab2;
bool modtab1 = true;
bool bandotab;
bool manhinhtongket;
uint64_t HackMapChuanOffset, DungGameOffset, HienbotroOffset, IsHostProfileOffset, HienrankOffset, Ulti1Offset, Ulti2Offset;