name: Build Theos Project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Cập nhật thành v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          
      - name: Download iOS SDK
        run: |
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          
      - name: Build Project (Make)
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Cập nhật thành v4
        with:
          name: TruongMods_Compiled
          path: .theos/obj/debug/ # File dylib/framework sẽ nằm ở đây
